name: Run pytest on PR

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    #env:
    #  working-directory: /home/runner/work/

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Switch to Current Branch
      run: |
        git checkout ${{ env.BRANCH }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install -U pip
        pip install -r requirements.txt
        pip install -e .
        python setup.py install
        echo "[pwd]: ${PWD}"

    - name: Display Troubleshooting Information
      run: |
        echo "[workspace]: ${{ github.workspace }}"
        echo "[pwd]: ${PWD}"
        echo "[LS]: $(ls -al)"

    - name: Run tests and coverage report
      run: |
        # Note: the following commands have three entirely different instances
        # of the "-m" flag. These are positionally required!
        echo "[pwd]: ${PWD}"
        export PYTHONPATH=$PWD/suny485
        echo "[pythonpath]: ${PYTHONPATH}"
        echo "!! run pytest and exclude any live API tests !!"
        coverage run -m pytest -m 'not live_api' --tb=short
        echo "!! run coverage report"
        coverage report -m

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
